version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: email-boot-app
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xmx512m -Xms256m
